/**
 * @class Vitared.store.Searchs
 * @extends Ext.data.Store
 * This is the store to handle the searchs
 * @author oswaldo@codetlan.com
 * @codetlan
 */
Ext.define('Vitared.store.City', {
    extend: 'Ext.data.Store',
    config: {
        fields: [
            {name: "text", type: "string"},
            {name: "value", type: "string"},
            {name: "estado", type: "int"}
        ],
        data: [
            {text: 'Aguascalientes', value: 'Aguascalientes', estado: 1},
            {text: 'Asientos', value: 'Asientos', estado: 1},
            {text: 'Calvillo', value: 'Calvillo', estado: 1},
            {text: 'Cosío', value: 'Cosío', estado: 1},
            {text: 'Jesús María', value: 'Jesús María', estado: 1},
            {text: 'Pabellón de Arteaga', value: 'Pabellón de Arteaga', estado: 1},
            {text: 'Rincón de Romos', value: 'Rincón de Romos', estado: 1},
            {text: 'San Francisco de los Romo', value: 'San Francisco de los Romo', estado: 1},
            {text: 'Tepezalá', value: 'Tepezalá', estado: 1},
            {text: 'Ensenada', value: 'Ensenada', estado: 2},
            {text: 'Mexicali', value: 'Mexicali', estado: 2},
            {text: 'Playas de Rosarito', value: 'Playas de Rosarito', estado: 2},
            {text: 'Rodolfo Sánchez T. (Maneadero)', value: 'Rodolfo Sánchez T. (Maneadero)', estado: 2},
            {text: 'San Felipe', value: 'San Felipe', estado: 2},
            {text: 'Tecate', value: 'Tecate', estado: 2},
            {text: 'Tijuana', value: 'Tijuana', estado: 2},
            {text: 'Cabo San Lucas', value: 'Cabo San Lucas', estado: 3},
            {text: 'Ciudad Constitución', value: 'Ciudad Constitución', estado: 3},
            {text: 'Guerrero Negro', value: 'Guerrero Negro', estado: 3},
            {text: 'Heroica Mulegé', value: 'Heroica Mulegé', estado: 3},
            {text: 'La Paz', value: 'La Paz', estado: 3},
            {text: 'Loreto', value: 'Loreto', estado: 3},
            {text: 'Puerto Adolfo López Mateos', value: 'Puerto Adolfo López Mateos', estado: 3},
            {text: 'San Ignacio', value: 'San Ignacio', estado: 3},
            {text: 'San José del Cabo', value: 'San José del Cabo', estado: 3},
            {text: 'Todos Santos', value: 'Todos Santos', estado: 3},
            {text: 'Villa Alberto Andrés Alvarado Arámburo', value: 'Villa Alberto Andrés Alvarado Arámburo', estado: 3},
            {text: 'Calkini', value: 'Calkini', estado: 4},
            {text: 'Candelaria', value: 'Candelaria', estado: 4},
            {text: 'Champotón', value: 'Champotón', estado: 4},
            {text: 'Ciudad del Carmen', value: 'Ciudad del Carmen', estado: 4},
            {text: 'Escárcega', value: 'Escárcega', estado: 4},
            {text: 'Hecelchakán', value: 'Hecelchakán', estado: 4},
            {text: 'Hopelchén', value: 'Hopelchén', estado: 4},
            {text: 'Pomuch', value: 'Pomuch', estado: 4},
            {text: 'Sabancuy', value: 'Sabancuy', estado: 4},
            {text: 'San Francisco de Campeche', value: 'San Francisco de Campeche', estado: 4},
            {text: 'Acala', value: 'Acala', estado: 5},
            {text: 'Arriaga', value: 'Arriaga', estado: 5},
            {text: 'Cacahoatán', value: 'Cacahoatán', estado: 5},
            {text: 'Chiapa de Corzo', value: 'Chiapa de Corzo', estado: 5},
            {text: 'Cintalapa de Figueroa', value: 'Cintalapa de Figueroa', estado: 5},
            {text: 'Comitán de Domínguez', value: 'Comitán de Domínguez', estado: 5},
            {text: 'Huixtla', value: 'Huixtla', estado: 5},
            {text: 'Jiquipilas', value: 'Jiquipilas', estado: 5},
            {text: 'Las Margaritas', value: 'Las Margaritas', estado: 5},
            {text: 'Las Rosas', value: 'Las Rosas', estado: 5},
            {text: 'Mapastepec', value: 'Mapastepec', estado: 5},
            {text: 'Motozintla de Mendoza', value: 'Motozintla de Mendoza', estado: 5},
            {text: 'Ocosingo', value: 'Ocosingo', estado: 5},
            {text: 'Ocozocoautla de Espinosa', value: 'Ocozocoautla de Espinosa', estado: 5},
            {text: 'Palenque', value: 'Palenque', estado: 5},
            {text: 'Pichucalco', value: 'Pichucalco', estado: 5},
            {text: 'Pijijiapan', value: 'Pijijiapan', estado: 5},
            {text: 'Puerto Madero (San Benito)', value: 'Puerto Madero (San Benito)', estado: 5},
            {text: 'San Cristóbal de las Casas', value: 'San Cristóbal de las Casas', estado: 5},
            {text: 'Tapachula de Córdova y Ordóñez', value: 'Tapachula de Córdova y Ordóñez', estado: 5},
            {text: 'Tonalá', value: 'Tonalá', estado: 5},
            {text: 'Tuxtla Gutiérrez', value: 'Tuxtla Gutiérrez', estado: 5},
            {text: 'Venustiano Carranza', value: 'Venustiano Carranza', estado: 5},
            {text: 'Villaflores', value: 'Villaflores', estado: 5},
            {text: 'Bachíniva', value: 'Bachíniva', estado: 6},
            {text: 'Chiahuahua', value: 'Chiahuahua', estado: 6},
            {text: 'Colonia Anáhuac', value: 'Colonia Anáhuac', estado: 6},
            {text: 'Cuauhtémoc', value: 'Cuauhtémoc', estado: 6},
            {text: 'Delicias', value: 'Delicias', estado: 6},
            {text: 'Hidalgo del Parral', value: 'Hidalgo del Parral', estado: 6},
            {text: 'José Mariano Jiménez', value: 'José Mariano Jiménez', estado: 6},
            {text: 'Juan Aldama', value: 'Juan Aldama', estado: 6},
            {text: 'Juárez', value: 'Juárez', estado: 6},
            {text: 'Madera', value: 'Madera', estado: 6},
            {text: 'Manuel Ojinaga', value: 'Manuel Ojinaga', estado: 6},
            {text: 'Nuevo Casas Grandes', value: 'Nuevo Casas Grandes', estado: 6},
            {text: 'Santa Rosalía de Camargo', value: 'Santa Rosalía de Camargo', estado: 6},
            {text: 'Saucillo', value: 'Saucillo', estado: 6},
            {text: 'Allende', value: 'Allende', estado: 7},
            {text: 'Arteaga', value: 'Arteaga', estado: 7},
            {text: 'Castaños', value: 'Castaños', estado: 7},
            {text: 'Ciudad Acuña', value: 'Ciudad Acuña', estado: 7},
            {text: 'Ciudad Melchor Múzquiz', value: 'Ciudad Melchor Múzquiz', estado: 7},
            {text: 'Cuatro Ciénegas de Carranza', value: 'Cuatro Ciénegas de Carranza', estado: 7},
            {text: 'Francisco I. Madero (Chávez)', value: 'Francisco I. Madero (Chávez)', estado: 7},
            {text: 'Frontera', value: 'Frontera', estado: 7},
            {text: 'Matamoros', value: 'Matamoros', estado: 7},
            {text: 'Monclova', value: 'Monclova', estado: 7},
            {text: 'Morelos', value: 'Morelos', estado: 7},
            {text: 'Nadadores', value: 'Nadadores', estado: 7},
            {text: 'Nava', value: 'Nava', estado: 7},
            {text: 'Nueva Rosita', value: 'Nueva Rosita', estado: 7},
            {text: 'Parras de la Fuente', value: 'Parras de la Fuente', estado: 7},
            {text: 'Piedras Negras', value: 'Piedras Negras', estado: 7},
            {text: 'Ramos Arizpe', value: 'Ramos Arizpe', estado: 7},
            {text: 'Sabinas', value: 'Sabinas', estado: 7},
            {text: 'Saltillo', value: 'Saltillo', estado: 7},
            {text: 'San Buenaventura', value: 'San Buenaventura', estado: 7},
            {text: 'San Pedro', value: 'San Pedro', estado: 7},
            {text: 'Torreón', value: 'Torreón', estado: 7},
            {text: 'Viesca', value: 'Viesca', estado: 7},
            {text: 'Zaragoza', value: 'Zaragoza', estado: 7},
            {text: 'Ciudad de Armería', value: 'Ciudad de Armería', estado: 8},
            {text: 'Ciudad de Villa de Álvarez', value: 'Ciudad de Villa de Álvarez', estado: 8},
            {text: 'Colima', value: 'Colima', estado: 8},
            {text: 'Manzanillo', value: 'Manzanillo', estado: 8},
            {text: 'Tecoman', value: 'Tecoman', estado: 8},
            {text: 'Álvaro Obregón', value: 'Álvaro Obregón', estado: 9},
            {text: 'Azcapotzalco', value: 'Azcapotzalco', estado: 9},
            {text: 'Benito Juárez', value: 'Benito Juárez', estado: 9},
            {text: 'Coyoacán', value: 'Coyoacán', estado: 9},
            {text: 'Cuajimalpa', value: 'Cuajimalpa', estado: 9},
            {text: 'Cuauhtémoc', value: 'Cuauhtémoc', estado: 9},
            {text: 'Gustavo A. Madero', value: 'Gustavo A. Madero', estado: 9},
            {text: 'Iztacalco', value: 'Iztacalco', estado: 9},
            {text: 'Iztapalapa', value: 'Iztapalapa', estado: 9},
            {text: 'Magdalena Contreras', value: 'Magdalena Contreras', estado: 9},
            {text: 'Miguel Hidalgo', value: 'Miguel Hidalgo', estado: 9},
            {text: 'Milpa Alta', value: 'Milpa Alta', estado: 9},
            {text: 'Tláhuac', value: 'Tláhuac', estado: 9},
            {text: 'Tlalpan', value: 'Tlalpan', estado: 9},
            {text: 'Venustiano Carranza', value: 'Venustiano Carranza', estado: 9},
            {text: 'Xochimilco', value: 'Xochimilco', estado: 9},
            {text: 'Canatlán', value: 'Canatlán', estado: 10},
            {text: 'Ciudad Lerdo', value: 'Ciudad Lerdo', estado: 10},
            {text: 'El Salto', value: 'El Salto', estado: 10},
            {text: 'Francisco I. Madero', value: 'Francisco I. Madero', estado: 10},
            {text: 'Gómez Palacio', value: 'Gómez Palacio', estado: 10},
            {text: 'Nombre de Dios', value: 'Nombre de Dios', estado: 10},
            {text: 'Peñón Blanco', value: 'Peñón Blanco', estado: 10},
            {text: 'San Juan del Río del Centauro del Norte', value: 'San Juan del Río del Centauro del Norte', estado: 10},
            {text: 'Santa María del Oro', value: 'Santa María del Oro', estado: 10},
            {text: 'Santiago Papasquiaro', value: 'Santiago Papasquiaro', estado: 10},
            {text: 'Vicente Guerrero', value: 'Vicente Guerrero', estado: 10},
            {text: 'Victoria de Durango', value: 'Victoria de Durango', estado: 10},
            {text: 'Abasolo', value: 'Abasolo', estado: 11},
            {text: 'Acámbaro', value: 'Acámbaro', estado: 11},
            {text: 'Apaseo el Alto', value: 'Apaseo el Alto', estado: 11},
            {text: 'Apaseo el Grande', value: 'Apaseo el Grande', estado: 11},
            {text: 'Celaya', value: 'Celaya', estado: 11},
            {text: 'Ciudad Manuel Doblado', value: 'Ciudad Manuel Doblado', estado: 11},
            {text: 'Comonfort', value: 'Comonfort', estado: 11},
            {text: 'Cortazar', value: 'Cortazar', estado: 11},
            {text: 'Cuerámaro', value: 'Cuerámaro', estado: 11},
            {text: 'Doctor Mora', value: 'Doctor Mora', estado: 11},
            {text: 'Empalme Escobedo (Escobedo)', value: 'Empalme Escobedo (Escobedo)', estado: 11},
            {text: 'Guanajuato', value: 'Guanajuato', estado: 11},
            {text: 'Huanímaro', value: 'Huanímaro', estado: 11},
            {text: 'Irapuato', value: 'Irapuato', estado: 11},
            {text: 'Jaral del Progreso', value: 'Jaral del Progreso', estado: 11},
            {text: 'Jerécuaro', value: 'Jerécuaro', estado: 11},
            {text: 'León de los Aldama', value: 'León de los Aldama', estado: 11},
            {text: 'Marfil', value: 'Marfil', estado: 11},
            {text: 'Moroleón', value: 'Moroleón', estado: 11},
            {text: 'Purísima de Bustos', value: 'Purísima de Bustos', estado: 11},
            {text: 'Pénjamo', value: 'Pénjamo', estado: 11},
            {text: 'Rincón de Tamayo', value: 'Rincón de Tamayo', estado: 11},
            {text: 'Romita', value: 'Romita', estado: 11},
            {text: 'Salamanca', value: 'Salamanca', estado: 11},
            {text: 'Salvatierra', value: 'Salvatierra', estado: 11},
            {text: 'San Diego de la Unión', value: 'San Diego de la Unión', estado: 11},
            {text: 'San Francisco del Rincón', value: 'San Francisco del Rincón', estado: 11},
            {text: 'San José Iturbide', value: 'San José Iturbide', estado: 11},
            {text: 'San Luis de la Paz', value: 'San Luis de la Paz', estado: 11},
            {text: 'San Miguel de Allende', value: 'San Miguel de Allende', estado: 11},
            {text: 'Santa Cruz Juventino Rosas', value: 'Santa Cruz Juventino Rosas', estado: 11},
            {text: 'Santiago Maravatío', value: 'Santiago Maravatío', estado: 11},
            {text: 'Silao', value: 'Silao', estado: 11},
            {text: 'Tarandacuao', value: 'Tarandacuao', estado: 11},
            {text: 'Uriangato', value: 'Uriangato', estado: 11},
            {text: 'Valle de Santiago', value: 'Valle de Santiago', estado: 11},
            {text: 'Villagrán', value: 'Villagrán', estado: 11},
            {text: 'Yuriria', value: 'Yuriria', estado: 11},
            {text: 'Acapulco de Juárez', value: 'Acapulco de Juárez', estado: 12},
            {text: 'Arcelia', value: 'Arcelia', estado: 12},
            {text: 'Atoyac de Álvarez', value: 'Atoyac de Álvarez', estado: 12},
            {text: 'Ayutla de los Libres', value: 'Ayutla de los Libres', estado: 12},
            {text: 'Azoyú', value: 'Azoyú', estado: 12},
            {text: 'Buenavista de Cuellar', value: 'Buenavista de Cuellar', estado: 12},
            {text: 'Chilapa de Álvarez', value: 'Chilapa de Álvarez', estado: 12},
            {text: 'Chilpancingo de los Bravo', value: 'Chilpancingo de los Bravo', estado: 12},
            {text: 'Ciudad Altamirano', value: 'Ciudad Altamirano', estado: 12},
            {text: 'Ciudad Apaxtla de Castrejón', value: 'Ciudad Apaxtla de Castrejón', estado: 12},
            {text: 'Copala', value: 'Copala', estado: 12},
            {text: 'Coyuca de Benítez', value: 'Coyuca de Benítez', estado: 12},
            {text: 'Coyuca de Catalán', value: 'Coyuca de Catalán', estado: 12},
            {text: 'Cruz Grande', value: 'Cruz Grande', estado: 12},
            {text: 'Cuajinicuilapa', value: 'Cuajinicuilapa', estado: 12},
            {text: 'Cutzamala de Pinzón', value: 'Cutzamala de Pinzón', estado: 12},
            {text: 'Huamuxtitlan', value: 'Huamuxtitlan', estado: 12},
            {text: 'Huitzuco', value: 'Huitzuco', estado: 12},
            {text: 'Iguala de la Independencia', value: 'Iguala de la Independencia', estado: 12},
            {text: 'La Unión', value: 'La Unión', estado: 12},
            {text: 'Marquelia', value: 'Marquelia', estado: 12},
            {text: 'Ocotito', value: 'Ocotito', estado: 12},
            {text: 'Olinalá', value: 'Olinalá', estado: 12},
            {text: 'Petatlán', value: 'Petatlán', estado: 12},
            {text: 'San Jerónimo de Juarez', value: 'San Jerónimo de Juarez', estado: 12},
            {text: 'San Luis Acatlán', value: 'San Luis Acatlán', estado: 12},
            {text: 'San Luis San Pedro', value: 'San Luis San Pedro', estado: 12},
            {text: 'San Luis de la Loma', value: 'San Luis de la Loma', estado: 12},
            {text: 'San Marcos', value: 'San Marcos', estado: 12},
            {text: 'Taxco de Alarcón', value: 'Taxco de Alarcón', estado: 12},
            {text: 'Teloloapan', value: 'Teloloapan', estado: 12},
            {text: 'Tepecoacuilco de Trujano', value: 'Tepecoacuilco de Trujano', estado: 12},
            {text: 'Tierra Colorada', value: 'Tierra Colorada', estado: 12},
            {text: 'Tixtla de Guerrero', value: 'Tixtla de Guerrero', estado: 12},
            {text: 'Tlapa de Comonfort', value: 'Tlapa de Comonfort', estado: 12},
            {text: 'Tlapehuala', value: 'Tlapehuala', estado: 12},
            {text: 'Técpan de Galeana', value: 'Técpan de Galeana', estado: 12},
            {text: 'Zihuatanejo', value: 'Zihuatanejo', estado: 12},
            {text: 'Zumpango del Río', value: 'Zumpango del Río', estado: 12},
            {text: 'Actopan', value: 'Actopan', estado: 13},
            {text: 'Apan', value: 'Apan', estado: 13},
            {text: 'Ciudad de Fray Bernardino de Sahagún', value: 'Ciudad de Fray Bernardino de Sahagún', estado: 13},
            {text: 'Cruz Azul', value: 'Cruz Azul', estado: 13},
            {text: 'Huejutla de Reyes', value: 'Huejutla de Reyes', estado: 13},
            {text: 'Ixmiquilpan', value: 'Ixmiquilpan', estado: 13},
            {text: 'Pachuca de Soto', value: 'Pachuca de Soto', estado: 13},
            {text: 'Santiago Tulantepec', value: 'Santiago Tulantepec', estado: 13},
            {text: 'Tepeapulco', value: 'Tepeapulco', estado: 13},
            {text: 'Tepeji del Rio', value: 'Tepeji del Rio', estado: 13},
            {text: 'Tizayuca', value: 'Tizayuca', estado: 13},
            {text: 'Tlaxcoapan', value: 'Tlaxcoapan', estado: 13},
            {text: 'Tula de Allende', value: 'Tula de Allende', estado: 13},
            {text: 'Tulancingo', value: 'Tulancingo', estado: 13},
            {text: 'Zimapan', value: 'Zimapan', estado: 13},
            {text: 'Acatlán de Juárez', value: 'Acatlán de Juárez', estado: 14},
            {text: 'Ahualulco de Mercado', value: 'Ahualulco de Mercado', estado: 14},
            {text: 'Ajijic', value: 'Ajijic', estado: 14},
            {text: 'Ameca', value: 'Ameca', estado: 14},
            {text: 'Arandas', value: 'Arandas', estado: 14},
            {text: 'Atotonilco el Alto', value: 'Atotonilco el Alto', estado: 14},
            {text: 'Autlán de Navarro', value: 'Autlán de Navarro', estado: 14},
            {text: 'Chapala', value: 'Chapala', estado: 14},
            {text: 'Cihuatlán', value: 'Cihuatlán', estado: 14},
            {text: 'Ciudad Guzmán', value: 'Ciudad Guzmán', estado: 14},
            {text: 'Cocula', value: 'Cocula', estado: 14},
            {text: 'Colotlán', value: 'Colotlán', estado: 14},
            {text: 'El Grullo', value: 'El Grullo', estado: 14},
            {text: 'El Quince (San José el Quince)', value: 'El Quince (San José el Quince)', estado: 14},
            {text: 'Etzatlán', value: 'Etzatlán', estado: 14},
            {text: 'Guadalajara', value: 'Guadalajara', estado: 14},
            {text: 'Huejuquilla el Alto', value: 'Huejuquilla el Alto', estado: 14},
            {text: 'Jalostitlán', value: 'Jalostitlán', estado: 14},
            {text: 'Jamay', value: 'Jamay', estado: 14},
            {text: 'Jocotepec', value: 'Jocotepec', estado: 14},
            {text: 'La Barca', value: 'La Barca', estado: 14},
            {text: 'La Resolana', value: 'La Resolana', estado: 14},
            {text: 'Lagos de Moreno', value: 'Lagos de Moreno', estado: 14},
            {text: 'Las Pintitas', value: 'Las Pintitas', estado: 14},
            {text: 'Magdalena', value: 'Magdalena', estado: 14},
            {text: 'Ocotlán', value: 'Ocotlán', estado: 14},
            {text: 'Poncitlán', value: 'Poncitlán', estado: 14},
            {text: 'Puerto Vallarta', value: 'Puerto Vallarta', estado: 14},
            {text: 'San Diego de Alejandría', value: 'San Diego de Alejandría', estado: 14},
            {text: 'San Ignacio Cerro Gordo', value: 'San Ignacio Cerro Gordo', estado: 14},
            {text: 'San José el Verde (El verde)', value: 'San José el Verde (El verde)', estado: 14},
            {text: 'San Juan de los Lagos', value: 'San Juan de los Lagos', estado: 14},
            {text: 'San Julián', value: 'San Julián', estado: 14},
            {text: 'San Miguel el Alto', value: 'San Miguel el Alto', estado: 14},
            {text: 'Sayula', value: 'Sayula', estado: 14},
            {text: 'Tala', value: 'Tala', estado: 14},
            {text: 'Talpa de Allende', value: 'Talpa de Allende', estado: 14},
            {text: 'Tamazula de Gordiano', value: 'Tamazula de Gordiano', estado: 14},
            {text: 'Tecalitlán', value: 'Tecalitlán', estado: 14},
            {text: 'Teocaltiche', value: 'Teocaltiche', estado: 14},
            {text: 'Tepatitlán de Morelos', value: 'Tepatitlán de Morelos', estado: 14},
            {text: 'Tequila', value: 'Tequila', estado: 14},
            {text: 'Tlajomulco de Zuñiga', value: 'Tlajomulco de Zuñiga', estado: 14},
            {text: 'Tlaquepaque', value: 'Tlaquepaque', estado: 14},
            {text: 'Tototlán', value: 'Tototlán', estado: 14},
            {text: 'Tuxpan', value: 'Tuxpan', estado: 14},
            {text: 'Unión de San Antonio', value: 'Unión de San Antonio', estado: 14},
            {text: 'Valle de Guadalupe', value: 'Valle de Guadalupe', estado: 14},
            {text: 'Villa Corona', value: 'Villa Corona', estado: 14},
            {text: 'Villa Hidalgo', value: 'Villa Hidalgo', estado: 14},
            {text: 'Yahualica de González Gallo', value: 'Yahualica de González Gallo', estado: 14},
            {text: 'Zocoalco de Torres', value: 'Zocoalco de Torres', estado: 14},
            {text: 'Zapopan', value: 'Zapopan', estado: 14},
            {text: 'Zapotiltic', value: 'Zapotiltic', estado: 14},
            {text: 'Apatzingán de la Constitución', value: 'Apatzingán de la Constitución', estado: 15},
            {text: 'Ciudad Hidalgo', value: 'Ciudad Hidalgo', estado: 15},
            {text: 'Ciudad Lázaro Cárdenas', value: 'Ciudad Lázaro Cárdenas', estado: 15},
            {text: 'Cotija de la Paz', value: 'Cotija de la Paz', estado: 15},
            {text: 'Cuitzeo del Porvenir', value: 'Cuitzeo del Porvenir', estado: 15},
            {text: 'Heroica Zitácuaro', value: 'Heroica Zitácuaro', estado: 15},
            {text: 'Huetamo de Núñez', value: 'Huetamo de Núñez', estado: 15},
            {text: 'Jacona de Plancarte', value: 'Jacona de Plancarte', estado: 15},
            {text: 'Jiquilpan de Juárez', value: 'Jiquilpan de Juárez', estado: 15},
            {text: 'La Piedad de Cabadas', value: 'La Piedad de Cabadas', estado: 15},
            {text: 'Las Guacamayas', value: 'Las Guacamayas', estado: 15},
            {text: 'Los Reyes del Salgado', value: 'Los Reyes del Salgado', estado: 15},
            {text: 'Maravatío de Ocampo', value: 'Maravatío de Ocampo', estado: 15},
            {text: 'Nueva Italia de Ruiz', value: 'Nueva Italia de Ruiz', estado: 15},
            {text: 'Paracho de Verduzco', value: 'Paracho de Verduzco', estado: 15},
            {text: 'Puruándiro', value: 'Puruándiro', estado: 15},
            {text: 'Pátzcuaro', value: 'Pátzcuaro', estado: 15},
            {text: 'Sahuayo de Morelos', value: 'Sahuayo de Morelos', estado: 15},
            {text: 'Tacámbaro de Codallos', value: 'Tacámbaro de Codallos', estado: 15},
            {text: 'Tandancícuaro de Arista', value: 'Tandancícuaro de Arista', estado: 15},
            {text: 'Uruapan', value: 'Uruapan', estado: 15},
            {text: 'Yurécuaro', value: 'Yurécuaro', estado: 15},
            {text: 'Zacapu', value: 'Zacapu', estado: 15},
            {text: 'Zamora de Hidalgo', value: 'Uruapan', estado: 15},
            {text: 'Zinapécuaro de Figueroa', value: 'Zinapécuaro de Figueroa', estado: 15},
            {text: 'Cuautla (Cuautla de Morelos)', value: 'Cuautla (Cuautla de Morelos)', estado: 16},
            {text: 'Cuernavaca', value: 'Cuernavaca', estado: 16},
            {text: 'Galeana', value: 'Galeana', estado: 16},
            {text: 'Jojutla', value: 'Jojutla', estado: 16},
            {text: 'Puente de Ixtla', value: 'Puente de Ixtla', estado: 16},
            {text: 'Santa Rosa Treinta', value: 'Santa Rosa Treinta', estado: 16},
            {text: 'Tlaqutenango', value: 'Tlaqutenango', estado: 16},
            {text: 'Zacatepec de Hidalgo', value: 'Zacatepec de Hidalgo', estado: 16},
            {text: 'Almoloya de Juárez', value: 'Almoloya de Juárez', estado: 17},
            {text: 'Amatepec', value: 'Amatepec', estado: 17},
            {text: 'Atizapán de Zaragoza', value: 'Atizapán de Zaragoza', estado: 17},
            {text: 'Capulhuac', value: 'Capulhuac', estado: 17},
            {text: 'Chalco de Díaz Covarrubias', value: 'Chalco de Díaz Covarrubias', estado: 17},
            {text: 'Chiconcuac', value: 'Chiconcuac', estado: 17},
            {text: 'Chimalhuacán', value: 'Chimalhuacán', estado: 17},
            {text: 'Ciudad Adolfo López Mateos', value: 'Ciudad Adolfo López Mateos', estado: 17},
            {text: 'Ciudad Nezahualcoyotl', value: 'Ciudad Nezahualcoyotl', estado: 17},
            {text: 'Coacalco de Berriozabal', value: 'Coacalco de Berriozabal', estado: 17},
            {text: 'Cuautitlán', value: 'Cuautitlán', estado: 17},
            {text: 'Cuautitlán Izcalli', value: 'Cuautitlán Izcalli', estado: 17},
            {text: 'Ecatepec de Morelos', value: 'Ecatepec de Morelos', estado: 17},
            {text: 'Huixquilucan de Degollado', value: 'Huixquilucan de Degollado', estado: 17},
            {text: 'Ixtapaluca', value: 'Ixtapaluca', estado: 17},
            {text: 'Juchitepec de Mariano Riva Palacio', value: 'Juchitepec de Mariano Riva Palacio', estado: 17},
            {text: 'Los Reyes Acaquilpan (La Paz)', value: 'Zacapu', estado: 17},
            {text: 'Melchor Ocampo', value: 'Melchor Ocampo', estado: 17},
            {text: 'Metepec', value: 'Metepec', estado: 17},
            {text: 'Naucalpan de Juárez', value: 'Naucalpan de Juárez', estado: 17},
            {text: 'Nezahualcóyotl', value: 'Nezahualcóyotl', estado: 17},
            {text: 'Ocoyoacac', value: 'Ocoyoacac', estado: 17},
            {text: 'San Mateo Atenco', value: 'San Mateo Atenco', estado: 17},
            {text: 'San Vicente Chicoloapan de Juárez', value: 'San Vicente Chicoloapan de Juárez', estado: 17},
            {text: 'Santa Maria Tultepec', value: 'Santa Maria Tultepec', estado: 17},
            {text: 'Tecamac de Felipe Villanueva', value: 'Tecamac de Felipe Villanueva', estado: 17},
            {text: 'Tejupilco de Hidalgo', value: 'Tejupilco de Hidalgo', estado: 17},
            {text: 'Tepotzotlán', value: 'Tepotzotlán', estado: 17},
            {text: 'Tequixquiac', value: 'Tequixquiac', estado: 17},
            {text: 'Texcoco de Mora', value: 'Texcoco de Mora', estado: 17},
            {text: 'Tlalnepantla de Baz', value: 'Tlalnepantla de Baz', estado: 17},
            {text: 'Toluca de Lerdo', value: 'Toluca de Lerdo', estado: 17},
            {text: 'Tultitlan de Mariano Escobedo', value: 'Tultitlan de Mariano Escobedo', estado: 17},
            {text: 'Valle de Chalco Solidaridad', value: 'Valle de Chalco Solidaridad', estado: 17},
            {text: 'Villa Nicolás Romero', value: 'Villa Nicolás Romero', estado: 17},
            {text: 'Xonacatlán', value: 'Xonacatlán', estado: 17},
            {text: 'Zumpango', value: 'Zumpango', estado: 17},
            {text: 'Acaponeta', value: 'Acaponeta', estado: 18},
            {text: 'Ahuacatlán', value: 'Ahuacatlán', estado: 18},
            {text: 'Bucerías', value: 'Bucerías', estado: 18},
            {text: 'Compostela', value: 'Compostela', estado: 18},
            {text: 'Francisco I. Madero (Puga)', value: 'Francisco I. Madero (Puga)', estado: 18},
            {text: 'Ixtlán del Río', value: 'Ixtlán del Río', estado: 18},
            {text: 'Jala', value: 'Jala', estado: 18},
            {text: 'La peñita de Jaltemba', value: 'La peñita de Jaltemba', estado: 18},
            {text: 'Las Varas', value: 'Las Varas', estado: 18},
            {text: 'Ruiz', value: 'Ruiz', estado: 18},
            {text: 'San Blas', value: 'San Blas', estado: 18},
            {text: 'San pedro Lagunillas', value: 'San pedro Lagunillas', estado: 18},
            {text: 'Santiago Ixcuintla', value: 'Santiago Ixcuintla', estado: 18},
            {text: 'Tecuala', value: 'Tecuala', estado: 18},
            {text: 'Tepic', value: 'Tepic', estado: 18},
            {text: 'Villa Hidalgo (El Nuevo)', value: 'Villa Hidalgo (El Nuevo)', estado: 18},
            {text: 'Xalisco', value: 'Xalisco', estado: 18},
            {text: 'Anáhuac', value: 'Anáhuac', estado: 19},
            {text: 'Cadereyta Jiménez', value: 'Cadereyta Jiménez', estado: 19},
            {text: 'Ciudad Apodaca', value: 'Ciudad Apodaca', estado: 19},
            {text: 'Ciudad Benito Juárez', value: 'Ciudad Benito Juárez', estado: 19},
            {text: 'Ciudad General Escobedo', value: 'Ciudad General Escobedo', estado: 19},
            {text: 'Ciudad Sabinas Hidalgo', value: 'Ciudad Sabinas Hidalgo', estado: 19},
            {text: 'Ciudad Santa Catarina', value: 'Ciudad Santa Catarina', estado: 19},
            {text: 'Ciénega de Flores', value: 'Ciénega de Flores', estado: 19},
            {text: 'Doctor Arroyo', value: 'Doctor Arroyo', estado: 19},
            {text: 'El cercado', value: 'El cercado', estado: 19},
            {text: 'García', value: 'García', estado: 19},
            {text: 'Guadalupe', value: 'Guadalupe', estado: 19},
            {text: 'Hualahuises', value: 'Hualahuises', estado: 19},
            {text: 'Linares', value: 'Linares', estado: 19},
            {text: 'Montemorelos', value: 'Montemorelos', estado: 19},
            {text: 'Monterrey', value: 'Monterrey', estado: 19},
            {text: 'San Nicolás de los Garza', value: 'San Nicolás de los Garza', estado: 19},
            {text: 'San Pedro Garza García', value: 'San Pedro Garza García', estado: 19},
            {text: 'Santiago', value: 'Santiago', estado: 19},
            {text: 'Asunción Nochixtlán', value: 'Asunción Nochixtlán', estado: 20},
            {text: 'Bahias de Huatulco', value: 'Bahias de Huatulco', estado: 20},
            {text: 'Chahuites', value: 'Chahuites', estado: 20},
            {text: 'Ciudad Ixtepec', value: 'Ciudad Ixtepec', estado: 20},
            {text: 'Cosolapa', value: 'Cosolapa', estado: 20},
            {text: 'Cuilápam de Guerrero', value: 'Cuilápam de Guerrero', estado: 20},
            {text: 'El Camarón', value: 'El Camarón', estado: 20},
            {text: 'El Rosario', value: 'El Rosario', estado: 20},
            {text: 'Heroica Ciudad de Ejutla de Crespo', value: 'Heroica Ciudad de Ejutla de Crespo', estado: 20},
            {text: 'Heroica Ciudad de Huajuapan de León', value: 'Heroica Ciudad de Huajuapan de León', estado: 20},
            {text: 'Heroica Ciudad de Tlaxiaco', value: 'Heroica Ciudad de Tlaxiaco', estado: 20},
            {text: 'Juchitán (Juchitán de Zaragoza)', value: 'Juchitán (Juchitán de Zaragoza)', estado: 20},
            {text: 'Lagunas', value: 'Lagunas', estado: 20},
            {text: 'Loma Bonita', value: 'Loma Bonita', estado: 20},
            {text: 'Mariscala de Juárez', value: 'Mariscala de Juárez', estado: 20},
            {text: 'Matías Romero Avendaño', value: 'Matías Romero Avendaño', estado: 20},
            {text: 'Miahuatlán de Porfirio Díaz', value: 'Miahuatlán de Porfirio Díaz', estado: 20},
            {text: 'Natividad', value: 'Natividad', estado: 20},
            {text: 'Oaxaca de Juárez', value: 'Oaxaca de Juárez', estado: 20},
            {text: 'Ocotlán de Morelos', value: 'Ocotlán de Morelos', estado: 20},
            {text: 'Puerto Escondido', value: 'Puerto Escondido', estado: 20},
            {text: 'Putla Villa de Guerrero', value: 'Putla Villa de Guerrero', estado: 20},
            {text: 'Rio Grande o Piedra Parada', value: 'Rio Grande o Piedra Parada', estado: 20},
            {text: 'Salina Cruz', value: 'Salina Cruz', estado: 20},
            {text: 'San Antonio de la Cal', value: 'San Antonio de la Cal', estado: 20},
            {text: 'San Blas Atempa', value: 'San Blas Atempa', estado: 20},
            {text: 'San Felipe Jalapa de Díaz', value: 'San Felipe Jalapa de Díaz', estado: 20},
            {text: 'San Francisco Ixhuatán', value: 'San Francisco Ixhuatán', estado: 20},
            {text: 'San Francisco Telixtlahuaca', value: 'San Francisco Telixtlahuaca', estado: 20},
            {text: 'San Juan Bautista Cuicatlán', value: 'San Juan Bautista Cuicatlán', estado: 20},
            {text: 'San Juan Bautista Tuxtepec', value: 'San Juan Bautista Tuxtepec', estado: 20},
            {text: 'San Juan Bautista Valle Nacional', value: 'San Juan Bautista Valle Nacional', estado: 20},
            {text: 'San Juan Bautista lo de Soto', value: 'San Juan Bautista lo de Soto', estado: 20},
            {text: 'San Juan Cacahuatepec', value: 'San Juan Cacahuatepec', estado: 20},
            {text: 'San Miguel el Grande', value: 'San Miguel el Grande', estado: 20},
            {text: 'San Pablo Huitzo', value: 'San Pablo Huitzo', estado: 20},
            {text: 'San Pablo Villa de Mitla', value: 'San Pablo Villa de Mitla', estado: 20},
            {text: 'San Pedro Mixtepec -Dto. 22-', value: 'San Pedro Mixtepec -Dto. 22-', estado: 20},
            {text: 'San Pedro Pochutla', value: 'San Pedro Pochutla', estado: 20},
            {text: 'San Pedro Tapanatepec', value: 'San Pedro Tapanatepec', estado: 20},
            {text: 'San Pedro Totolapa', value: 'San Pedro Totolapa', estado: 20},
            {text: 'San Sebastián Tecomaxtlahuaca', value: 'San Sebastián Tecomaxtlahuaca', estado: 20},
            {text: 'Santa Cruz Itundujia', value: 'Santa Cruz Itundujia', estado: 20},
            {text: 'Santa Lucia del Camino', value: 'Santa Lucia del Camino', estado: 20},
            {text: 'Santa Maria Huatulco', value: 'Santa Maria Huatulco', estado: 20},
            {text: 'Santiago Jamiltepec', value: 'Santiago Jamiltepec', estado: 20},
            {text: 'Santiago Juxtlahuaca', value: 'Santiago Juxtlahuaca', estado: 20},
            {text: 'Santiago Pinotepa Nacional', value: 'Santiago Pinotepa Nacional', estado: 20},
            {text: 'Santiago Suchilquitongo', value: 'Santiago Suchilquitongo', estado: 20},
            {text: 'Santo Domingo Tehuantepec', value: 'Santo Domingo Tehuantepec', estado: 20},
            {text: 'Teotitlán de Flores Magón', value: 'Teotitlán de Flores Magón', estado: 20},
            {text: 'Tlacolula de Matamoros', value: 'Tlacolula de Matamoros', estado: 20},
            {text: 'Unión Hidalgo', value: 'Unión Hidalgo', estado: 20},
            {text: 'Vicente Camalote', value: 'Vicente Camalote', estado: 20},
            {text: 'Villa Sola de Vega', value: 'Villa Sola de Vega', estado: 20},
            {text: 'Villa de Tamazulápam del Progreso', value: 'Villa de Tamazulápam del Progreso', estado: 20},
            {text: 'Villa de Zaachila', value: 'Villa de Zaachila', estado: 20},
            {text: 'Zimatlán de Álvarez', value: 'Zimatlán de Álvarez', estado: 20},
            {text: 'Acatlán de Osorio', value: 'Acatlán de Osorio', estado: 21},
            {text: 'Amozoc', value: 'Amozoc', estado: 21},
            {text: 'Atlixco', value: 'Atlixco', estado: 21},
            {text: 'Ciudad Serdán', value: 'Ciudad Serdán', estado: 21},
            {text: 'Cuautlancingo', value: 'Cuautlancingo', estado: 21},
            {text: 'Huachinango', value: 'Huachinango', estado: 21},
            {text: 'Izucar de Matamoros', value: 'Izucar de Matamoros', estado: 21},
            {text: 'Puebla (Heroica Puebla)', value: 'Puebla (Heroica Puebla)', estado: 21},
            {text: 'San Andrés Cholula', value: 'San Andrés Cholula', estado: 21},
            {text: 'San Martín Texmelucan de Labastida', value: 'San Martín Texmelucan de Labastida', estado: 21},
            {text: 'San Pedro Cholula', value: 'San Pedro Cholula', estado: 21},
            {text: 'Tecamachalco', value: 'Tecamachalco', estado: 21},
            {text: 'Tehuacan', value: 'Tehuacan', estado: 21},
            {text: 'Tepeaca', value: 'Tepeaca', estado: 21},
            {text: 'Teziutlan', value: 'Teziutlan', estado: 21},
            {text: 'Xicotepec', value: 'Xicotepec', estado: 21},
            {text: 'Zacatlán', value: 'Zacatlán', estado: 21},
            {text: 'El Pueblito', value: 'El Pueblito', estado: 22},
            {text: 'Querétaro', value: 'Querétaro', estado: 22},
            {text: 'San Juan del Rio', value: 'San Juan del Rio', estado: 22},
            {text: 'Bacalar', value: 'Bacalar', estado: 23},
            {text: 'Cancún', value: 'Cancún', estado: 23},
            {text: 'Chetumal', value: 'Chetumal', estado: 23},
            {text: 'Cozumel', value: 'Cozumel', estado: 23},
            {text: 'Felipe Carrillo Puerto', value: 'Felipe Carrillo Puerto', estado: 23},
            {text: 'Isla Mujeres', value: 'Isla Mujeres', estado: 23},
            {text: 'Kantunilkin', value: 'Kantunilkin', estado: 23},
            {text: 'Playa del Carmen', value: 'Playa del Carmen', estado: 23},
            {text: 'Cedral', value: 'Cedral', estado: 24},
            {text: 'Cerritos', value: 'Cerritos', estado: 24},
            {text: 'Charcas', value: 'Charcas', estado: 24},
            {text: 'Ciudad Valles', value: 'Ciudad Valles', estado: 24},
            {text: 'Ciudad del Maíz', value: 'Ciudad del Maíz', estado: 24},
            {text: 'Cárdenas', value: 'Cárdenas', estado: 24},
            {text: 'El Naranjo', value: 'El Naranjo', estado: 24},
            {text: 'Fracción el Refugio', value: 'Fracción el Refugio', estado: 24},
            {text: 'Matehuala', value: 'Matehuala', estado: 24},
            {text: 'Rioverde', value: 'Rioverde', estado: 24},
            {text: 'Salinas de Hidalgo', value: 'Salinas de Hidalgo', estado: 24},
            {text: 'San Luis Potosí', value: 'San Luis Potosí', estado: 24},
            {text: 'Santa María del Río', value: 'Santa María del Río', estado: 24},
            {text: 'Soledad de Graciano Sánchez', value: 'Soledad de Graciano Sánchez', estado: 24},
            {text: 'Tamasopo', value: 'Tamasopo', estado: 24},
            {text: 'Tamazunchale', value: 'Tamazunchale', estado: 24},
            {text: 'Tamuin', value: '', estado: 24},
            {text: 'Tierra Nueva', value: 'Tierra Nueva', estado: 24},
            {text: 'Villa de Reyes', value: 'Villa de Reyes', estado: 24},
            {text: 'Aguaruto', value: 'Aguaruto', estado: 25},
            {text: 'Ahome', value: 'Ahome', estado: 25},
            {text: 'Angostura', value: 'Angostura', estado: 25},
            {text: 'Choix', value: 'Choix', estado: 25},
            {text: 'Cosalá', value: 'Cosalá', estado: 25},
            {text: 'Culiacán Rosales', value: 'Culiacán Rosales', estado: 25},
            {text: 'Escuinapa de Hidalgo', value: 'Escuinapa de Hidalgo', estado: 25},
            {text: 'Estación Naranjo', value: 'Estación Naranjo', estado: 25},
            {text: 'Guamúchil', value: 'Guamúchil', estado: 25},
            {text: 'Guasave', value: 'Guasave', estado: 25},
            {text: 'Higuera de Zaragoza', value: 'Higuera de Zaragoza', estado: 25},
            {text: 'La Cruz', value: 'La Cruz', estado: 25},
            {text: 'Lic. Benito Juárez (Campo Gobierno)', value: 'Lic. Benito Juárez (Campo Gobierno)', estado: 25},
            {text: 'Los Mochis', value: 'Los Mochis', estado: 25},
            {text: 'Mazatlán', value: 'Mazatlán', estado: 25},
            {text: 'Mocorito', value: 'Mocorito', estado: 25},
            {text: 'Navolato', value: 'Navolato', estado: 25},
            {text: 'Quila', value: 'Quila', estado: 25},
            {text: 'Sinaloa de Leyva', value: 'Sinaloa de Leyva', estado: 25},
            {text: 'Agua Prieta', value: 'Agua Prieta', estado: 26},
            {text: 'Ciudad Obregón', value: 'Ciudad Obregón', estado: 26},
            {text: 'Émpalme', value: 'Émpalme', estado: 26},
            {text: 'Hermosillo', value: 'Hermosillo', estado: 26},
            {text: 'Heroica Caborca', value: 'Heroica Caborca', estado: 26},
            {text: 'Heroica Ciudad de Cananea', value: 'Heroica Ciudad de Cananea', estado: 26},
            {text: 'Heroica Guaymas', value: 'Heroica Guaymas', estado: 26},
            {text: 'Heroica Nogales', value: 'Heroica Nogales', estado: 26},
            {text: 'Huatabampo', value: 'Huatabampo', estado: 26},
            {text: 'Magdalena de Kino', value: 'Magdalena de Kino', estado: 26},
            {text: 'Navojoa', value: 'Navojoa', estado: 26},
            {text: 'Puerto Peñasco', value: 'Puerto Peñasco', estado: 26},
            {text: 'San Luis Río Colorado', value: 'San Luis Río Colorado', estado: 26},
            {text: 'Sonoita', value: 'Sonoita', estado: 26},
            {text: 'Comalcalco', value: 'Comalcalco', estado: 27},
            {text: 'Cunduacán', value: 'Cunduacán', estado: 27},
            {text: 'Emiliano Zapata', value: 'Emiliano Zapata', estado: 27},
            {text: 'Huimanguillo', value: 'Huimanguillo', estado: 27},
            {text: 'Jalapa de Méndez', value: 'Jalapa de Méndez', estado: 27},
            {text: 'Macuspana', value: 'Macuspana', estado: 27},
            {text: 'Paraíso', value: 'Paraíso', estado: 27},
            {text: 'Teapa', value: 'Teapa', estado: 27},
            {text: 'Tenosique de Pino Suárez', value: 'Tenosique de Pino Suárez', estado: 27},
            {text: 'Villahermosa', value: 'Villahermosa', estado: 27},
            {text: 'Altamira', value: 'Altamira', estado: 28},
            {text: 'Ciudad Camargo', value: 'Ciudad Camargo', estado: 28},
            {text: 'Ciudad Gustavo Díaz Ordaz', value: 'Ciudad Gustavo Díaz Ordaz', estado: 28},
            {text: 'Ciudad Madero', value: 'Ciudad Madero', estado: 28},
            {text: 'Ciudad Mante', value: 'Ciudad Mante', estado: 28},
            {text: 'Ciudad Miguel Alemán', value: 'Ciudad Miguel Alemán', estado: 28},
            {text: 'Ciudad Rio Bravo', value: 'Ciudad Rio Bravo', estado: 28},
            {text: 'Ciudad Tula', value: 'Ciudad Tula', estado: 28},
            {text: 'Ciudad Victoria', value: 'Ciudad Victoria', estado: 28},
            {text: 'Estación Manuel (Úrsulo Galván)', value: 'Estación Manuel (Úrsulo Galván)', estado: 28},
            {text: 'González', value: 'González', estado: 28},
            {text: 'Heroica Matamoros', value: 'Heroica Matamoros', estado: 28},
            {text: 'Jaumave', value: 'Jaumave', estado: 28},
            {text: 'Nueva Ciudad Guerrero', value: 'Nueva Ciudad Guerrero', estado: 28},
            {text: 'Nuevo Laredo', value: 'Nuevo Laredo', estado: 28},
            {text: 'Reynosa', value: 'Reynosa', estado: 28},
            {text: 'San Fernando', value: 'San Fernando', estado: 28},
            {text: 'Soto la Marina', value: 'Soto la Marina', estado: 28},
            {text: 'Tampico', value: 'Tampico', estado: 28},
            {text: 'Valle Hermoso', value: 'Valle Hermoso', estado: 28},
            {text: 'Xicoténcatl', value: 'Xicoténcatl', estado: 28},
            {text: 'Apizaco', value: 'Apizaco', estado: 29},
            {text: 'Calpulalpan', value: 'Calpulalpan', estado: 29},
            {text: 'Chiautempan', value: 'Chiautempan', estado: 29},
            {text: 'Huamantla', value: 'Huamantla', estado: 29},
            {text: 'Tlaxcala (Tlaxcala de Xicotencatl)', value: 'Tlaxcala (Tlaxcala de Xicotencatl)', estado: 29},
            {text: 'Villa Vicente Guerrero', value: 'Villa Vicente Guerrero', estado: 29},
            {text: 'Acayucan', value: 'Acayucan', estado: 30},
            {text: 'Agua Dulce', value: 'Agua Dulce', estado: 30},
            {text: 'Altotonga', value: 'Altotonga', estado: 30},
            {text: 'Alvarado', value: 'Alvarado', estado: 30},
            {text: 'Atoyac', value: 'Atoyac', estado: 30},
            {text: 'Banderilla', value: 'Banderilla', estado: 30},
            {text: 'Boca del Río', value: 'Boca del Río', estado: 30},
            {text: 'Carlos A. Carrillo', value: 'Carlos A. Carrillo', estado: 30},
            {text: 'Catemaco', value: 'Catemaco', estado: 30},
            {text: 'Cazones de Herrera', value: 'Cazones de Herrera', estado: 30},
            {text: 'Cerro Azul', value: 'Cerro Azul', estado: 30},
            {text: 'Coatepec', value: 'Coatepec', estado: 30},
            {text: 'Coatzacoalcos', value: 'Coatzacoalcos', estado: 30},
            {text: 'Coatzintla', value: 'Coatzintla', estado: 30},
            {text: 'Cosamaloapan', value: 'Cosamaloapan', estado: 30},
            {text: 'Cosoleacaque', value: 'Cosoleacaque', estado: 30},
            {text: 'Cuichapa', value: 'Cuichapa', estado: 30},
            {text: 'Cuitláhuac', value: 'Cuitláhuac', estado: 30},
            {text: 'Córdoba', value: 'Córdoba', estado: 30},
            {text: 'El Higo', value: 'El Higo', estado: 30},
            {text: 'Fortin de las Flores', value: '', estado: 30},
            {text: 'General Miguel Alemán (Potrero Nuevo)', value: '', estado: 30},
            {text: 'Gutiérrez Zamora', value: 'Gutiérrez Zamora', estado: 30},
            {text: 'Huatusco de Chicuellar', value: 'Huatusco de Chicuellar', estado: 30},
            {text: 'Huayacocotla', value: 'Huayacocotla', estado: 30},
            {text: 'Huiloapan de Cuauhtémoc', value: 'Huiloapan de Cuauhtémoc', estado: 30},
            {text: 'Isla', value: 'Isla', estado: 30},
            {text: 'Ixtaczoquitlán', value: 'Ixtaczoquitlán', estado: 30},
            {text: 'José Cardel', value: 'José Cardel', estado: 30},
            {text: 'Juan Díaz Covarrubias', value: 'Juan Díaz Covarrubias', estado: 30},
            {text: 'Juan Rodríguez Clara', value: 'Juan Rodríguez Clara', estado: 30},
            {text: 'Jáltipan de Morelos', value: 'Jáltipan de Morelos', estado: 30},
            {text: 'Las Choapas', value: 'Las Choapas', estado: 30},
            {text: 'Lerdo de Tejada', value: 'Lerdo de Tejada', estado: 30},
            {text: 'Minatitlán', value: 'Minatitlán', estado: 30},
            {text: 'Naranjos', value: 'Naranjos', estado: 30},
            {text: 'Nogales', value: 'Nogales', estado: 30},
            {text: 'Orizaba', value: 'Orizaba', estado: 30},
            {text: 'Papantla de Olarte', value: 'Papantla de Olarte', estado: 30},
            {text: 'Paraje Nuevo', value: 'Paraje Nuevo', estado: 30},
            {text: 'Paso de Ovejas', value: 'Paso de Ovejas', estado: 30},
            {text: 'Paso del Macho', value: 'Paso del Macho', estado: 30},
            {text: 'Platón Sánchez', value: 'Platón Sánchez', estado: 30},
            {text: 'Playa Vicente', value: 'Playa Vicente', estado: 30},
            {text: 'Poza Rica de Hidalgo', value: 'Poza Rica de Hidalgo', estado: 30},
            {text: 'Pánuco', value: 'Pánuco', estado: 30},
            {text: 'Río Blanco', value: 'Río Blanco', estado: 30},
            {text: 'San Andrés Tuxtla', value: 'San Andrés Tuxtla', estado: 30},
            {text: 'San Rafael', value: 'San Rafael', estado: 30},
            {text: 'Santiago Tuxtla', value: 'Santiago Tuxtla', estado: 30},
            {text: 'Sihuapan', value: 'Sihuapan', estado: 30},
            {text: 'soledad de Doblado', value: 'soledad de Doblado', estado: 30},
            {text: 'Tampico Alto', value: 'Tampico Alto', estado: 30},
            {text: 'Tantoyuca', value: 'Tantoyuca', estado: 30},
            {text: 'Tempoal de Sánchez', value: 'Tempoal de Sánchez', estado: 30},
            {text: 'Tezonapa', value: 'Tezonapa', estado: 30},
            {text: 'Tierra Blanca', value: 'Tierra Blanca', estado: 30},
            {text: 'Tihuatlan', value: 'Tihuatlan', estado: 30},
            {text: 'Tlacojalpan', value: 'Tlacojalpan', estado: 30},
            {text: 'Tlapacoyan', value: 'Tlapacoyan', estado: 30},
            {text: 'Tres valles', value: 'Tres valles', estado: 30},
            {text: 'Túxpam de Rodríguez Cano', value: 'Túxpam de Rodríguez Cano', estado: 30},
            {text: 'Veracruz', value: 'Veracruz', estado: 30},
            {text: 'Xalapa-Enriquez', value: 'Xalapa-Enriquez', estado: 30},
            {text: 'Yecuatla', value: 'Yecuatla', estado: 30},
            {text: 'Motul de Carrillo Puerto', value: 'Motul de Carrillo Puerto', estado: 31},
            {text: 'Mérida', value: 'Mérida', estado: 31},
            {text: 'Ticul', value: 'Ticul', estado: 31},
            {text: 'Tizimín', value: 'Tizimín', estado: 31},
            {text: 'Valladolid', value: 'Valladolid', estado: 31},
            {text: 'Ciudad Cuauhtémoc ', value: 'Ciudad Cuauhtémoc', estado: 32},
            {text: 'Fresnillo', value: 'Fresnillo', estado: 32},
            {text: 'Jalpa', value: 'Jalpa', estado: 32},
            {text: 'Jerez de García Salinas', value: 'Jerez de García Salinas', estado: 32},
            {text: 'Luis Moya', value: 'Luis Moya', estado: 32},
            {text: 'Moyahua de Estrada', value: 'Moyahua de Estrada', estado: 32},
            {text: 'Nochistlán de Mejía', value: 'Nochistlán de Mejía', estado: 32},
            {text: 'Ojocaliente', value: 'Ojocaliente', estado: 32},
            {text: 'Río Grande', value: 'Río Grande', estado: 32},
            {text: 'Sombrerete', value: 'Sombrerete', estado: 32},
            {text: 'Valparaiso', value: 'Valparaiso', estado: 32},
            {text: 'Villa de Cos', value: 'Villa de Cos', estado: 32},
            {text: 'Villanueva', value: 'Villanueva', estado: 32},
            {text: 'Víctor Rosales', value: 'Víctor Rosales', estado: 32},
            {text: 'Zacatecas', value: 'Zacatecas', estado: 32}
        ]
    }
});