/**
 * @class Vitared.store.Searchs
 * @extends Ext.data.Store
 * This is the store to handle the searchs
 * @author oswaldo@codetlan.com
 * @codetlan
 */
Ext.define('Vitared.store.City', {
    extend: 'Ext.data.Store',
    config: {
        fields: [
            {name: "text", type: "string"},
            {name: "value", type: "int"}
        ],
        data: [
            {"text":"Aguascalientes","value":1},
            {"text":"Asientos","value":1},
            {"text":"Calvillo","value":1},
            {"text":"Cosío","value":1},
            {"text":"Jesús María","value":1},
            {"text":"Pabellón de Arteaga","value":1},
            {"text":"Rincón de Romos","value":1},
            {"text":"San Francisco de los Romo","value":1},
            {"text":"Tepezalá","value":1},
            {"text":"Ensenada","value":2},
            {"text":"Mexicali","value":2},
            {"text":"Playas de Rosarito","value":2},
            {"text":"Rodolfo Sánchez T. (Maneadero)","value":2},
            {"text":"San Felipe","value":2},
            {"text":"Tecate","value":2},
            {"text":"Tijuana","value":2},
            {"text":"Cabo San Lucas","value":3},
            {"text":"Ciudad Constitución","value":3},
            {"text":"Guerrero Negro","value":3},
            {"text":"Heroica Mulegé","value":3},
            {"text":"La Paz","value":3},
            {"text":"Loreto","value":3},
            {"text":"Puerto Adolfo López Mateos","value":3},
            {"text":"San Ignacio","value":3},
            {"text":"San José del Cabo","value":3},
            {"text":"Todos Santos","value":3},
            {"text":"Villa Alberto Andrés Alvarado Arámburo","value":3},
            {"text":"Calkini","value":4},
            {"text":"Candelaria","value":4},
            {"text":"Champotón","value":4},
            {"text":"Ciudad del Carmen","value":4},
            {"text":"Escárcega","value":4},
            {"text":"Hecelchakán","value":4},
            {"text":"Hopelchén","value":4},
            {"text":"Pomuch","value":4},
            {"text":"Sabancuy","value":4},
            {"text":"San Francisco de Campeche","value":4},
            {"text":"Acala","value":5},
            {"text":"Arriaga","value":5},
            {"text":"Cacahoatán","value":5},
            {"text":"Chiapa de Corzo","value":5},
            {"text":"Cintalapa de Figueroa","value":5},
            {"text":"Comitán de Domínguez","value":5},
            {"text":"Huixtla","value":5},
            {"text":"Jiquipilas","value":5},
            {"text":"Las Margaritas","value":5},
            {"text":"Las Rosas","value":5},
            {"text":"Mapastepec","value":5},
            {"text":"Motozintla de Mendoza","value":5},
            {"text":"Ocosingo","value":5},
            {"text":"Ocozocoautla de Espinosa","value":5},
            {"text":"Palenque","value":5},
            {"text":"Pichucalco","value":5},
            {"text":"Pijijiapan","value":5},
            {"text":"Puerto Madero (San Benito)","value":5},
            {"text":"Reforma","value":5},
            {"text":"San Cristóbal de las Casas","value":5},
            {"text":"Tapachula de Córdova y Ordóñez","value":5},
            {"text":"Tonalá","value":5},
            {"text":"Tuxtla Gutiérrez","value":5},
            {"text":"Venustiano Carranza","value":5},
            {"text":"Villaflores","value":5},
            {"text":"Bachíniva","value":6},
            {"text":"Chihuahua","value":6},
            {"text":"Colonia Anáhuac","value":6},
            {"text":"Cuauhtémoc","value":6},
            {"text":"Delicias","value":6},
            {"text":"Hidalgo del Parral","value":6},
            {"text":"José Mariano Jiménez","value":6},
            {"text":"Juan Aldama","value":6},
            {"text":"Juárez","value":6},
            {"text":"Madera","value":6},
            {"text":"Manuel Ojinaga","value":6},
            {"text":"Nuevo Casas Grandes","value":6},
            {"text":"Santa Rosalía de Camargo","value":6},
            {"text":"Saucillo","value":6},
            {"text":"Allende","value":7},
            {"text":"Arteaga","value":7},
            {"text":"Castaños","value":7},
            {"text":"Ciudad Acuña","value":7},
            {"text":"Ciudad Melchor Múzquiz","value":7},
            {"text":"Cuatro Ciénegas de Carranza","value":7},
            {"text":"Francisco I. Madero (Chávez)","value":7},
            {"text":"Frontera","value":7},
            {"text":"Matamoros","value":7},
            {"text":"Monclova","value":7},
            {"text":"Morelos","value":7},
            {"text":"Nadadores","value":7},
            {"text":"Nava","value":7},
            {"text":"Nueva Rosita","value":7},
            {"text":"Parras de la Fuente","value":7},
            {"text":"Piedras Negras","value":7},
            {"text":"Ramos Arizpe","value":7},
            {"text":"Sabinas","value":7},
            {"text":"Saltillo","value":7},
            {"text":"San Buenaventura","value":7},
            {"text":"San Pedro","value":7},
            {"text":"Torreón","value":7},
            {"text":"Viesca","value":7},
            {"text":"Zaragoza","value":7},
            {"text":"Ciudad de Armería","value":8},
            {"text":"Ciudad de Villa de Álvarez","value":8},
            {"text":"Colima","value":8},
            {"text":"Manzanillo","value":8},
            {"text":"Tecoman","value":8},
            {"text":"Álvaro Obregón","value":9},
            {"text":"Azcapotzalco","value":9},
            {"text":"Benito Juárez","value":9},
            {"text":"Coyoacán","value":9},
            {"text":"Cuajimalpa","value":9},
            {"text":"Cuauhtémoc","value":9},
            {"text":"Gustavo A. Madero","value":9},
            {"text":"Iztacalco","value":9},
            {"text":"Iztapalapa","value":9},
            {"text":"Magdalena Contreras","value":9},
            {"text":"Miguel Hidalgo","value":9},
            {"text":"Milpa Alta","value":9},
            {"text":"Tlalpan","value":9},
            {"text":"Tláhuac","value":9},
            {"text":"Venustiano Carranza","value":9},
            {"text":"Xochimilco","value":9},
            {"text":"Canatlán","value":10},
            {"text":"Ciudad Lerdo","value":10},
            {"text":"El Salto","value":10},
            {"text":"Francisco I. Madero","value":10},
            {"text":"Gómez Palacio","value":10},
            {"text":"Nombre de Dios","value":10},
            {"text":"Peñón Blanco","value":10},
            {"text":"San Juan del Río del Centauro del Norte","value":10},
            {"text":"Santa María del Oro","value":10},
            {"text":"Santiago Papasquiaro","value":10},
            {"text":"Vicente Guerrero","value":10},
            {"text":"Victoria de Durango","value":10},
            {"text":"Abasolo","value":11},
            {"text":"Acámbaro","value":11},
            {"text":"Apaseo el Alto","value":11},
            {"text":"Apaseo el Grande","value":11},
            {"text":"Celaya","value":11},
            {"text":"Ciudad Manuel Doblado","value":11},
            {"text":"Comonfort","value":11},
            {"text":"Cortazar","value":11},
            {"text":"Cuerámaro","value":11},
            {"text":"Doctor Mora","value":11},
            {"text":"Empalme Escobedo (Escobedo)","value":11},
            {"text":"Guanajuato","value":11},
            {"text":"Huanímaro","value":11},
            {"text":"Irapuato","value":11},
            {"text":"Jaral del Progreso","value":11},
            {"text":"Jerécuaro","value":11},
            {"text":"León de los Aldama","value":11},
            {"text":"Marfil","value":11},
            {"text":"Moroleón","value":11},
            {"text":"Purísima de Bustos","value":11},
            {"text":"Pénjamo","value":11},
            {"text":"Rincón de Tamayo","value":11},
            {"text":"Romita","value":11},
            {"text":"Salamanca","value":11},
            {"text":"Salvatierra","value":11},
            {"text":"San Diego de la Unión","value":11},
            {"text":"San Francisco del Rincón","value":11},
            {"text":"San José Iturbide","value":11},
            {"text":"San Luis de la Paz","value":11},
            {"text":"San miguel de Allende","value":11},
            {"text":"Santa Cruz Juventino Rosas","value":11},
            {"text":"Santiago Maravatío","value":11},
            {"text":"Silao","value":11},
            {"text":"Tarandacuao","value":11},
            {"text":"Uriangato","value":11},
            {"text":"Valle de Santiago","value":11},
            {"text":"Villagrán","value":11},
            {"text":"Yuriria","value":11},
            {"text":"Acapulco de Juárez","value":12},
            {"text":"Arcelia","value":12},
            {"text":"Atoyac de Álvarez","value":12},
            {"text":"Ayutla de los Libres","value":12},
            {"text":"Azoyú","value":12},
            {"text":"Buenavista de Cuellar","value":12},
            {"text":"Chilapa de Álvarez","value":12},
            {"text":"Chilpancingo de los Bravo","value":12},
            {"text":"Ciudad Altamirano","value":12},
            {"text":"Ciudad Apaxtla de Castrejón","value":12},
            {"text":"Copala","value":12},
            {"text":"Coyuca de Benítez","value":12},
            {"text":"Coyuca de Catalán","value":12},
            {"text":"Cruz Grande","value":12},
            {"text":"Cuajinicuilapa","value":12},
            {"text":"Cutzamala de Pinzón","value":12},
            {"text":"Huamuxtitlan","value":12},
            {"text":"Huitzuco","value":12},
            {"text":"Iguala de la Independencia","value":12},
            {"text":"La Unión","value":12},
            {"text":"Marquelia","value":12},
            {"text":"Ocotito","value":12},
            {"text":"Olinalá","value":12},
            {"text":"Petatlán","value":12},
            {"text":"San Jerónimo de Juárez","value":12},
            {"text":"San Luis Acatlán","value":12},
            {"text":"San Luis San Pedro","value":12},
            {"text":"San Luis de la Loma","value":12},
            {"text":"San Marcos","value":12},
            {"text":"Taxco de Alarcón","value":12},
            {"text":"Teloloapan","value":12},
            {"text":"Tepecoacuilco de Trujano","value":12},
            {"text":"Tierra Colorada","value":12},
            {"text":"Tixtla de Guerrero","value":12},
            {"text":"Tlalixtaquilla","value":12},
            {"text":"Tlapa de Comonfort","value":12},
            {"text":"Tlapehuala","value":12},
            {"text":"Técpan de Galeana","value":12},
            {"text":"Zihuatanejo","value":12},
            {"text":"Zumpango del Río","value":12},
            {"text":"Actopan","value":13},
            {"text":"Apan","value":13},
            {"text":"Ciudad de Fray Bernardino de Sahagún","value":13},
            {"text":"Cruz Azul","value":13},
            {"text":"Huejutla de Reyes","value":13},
            {"text":"Ixmiquilpan","value":13},
            {"text":"Pachuca de Soto","value":13},
            {"text":"Santiago Tulantepec","value":13},
            {"text":"Tepeapulco","value":13},
            {"text":"Tepeji del Rio","value":13},
            {"text":"Tizayuca","value":13},
            {"text":"Tlaxcoapan","value":13},
            {"text":"Tula de Allende","value":13},
            {"text":"Tulancingo","value":13},
            {"text":"Zimapan","value":13},
            {"text":"Acatlán de Juárez","value":14},
            {"text":"Ahualulco de Mercado","value":14},
            {"text":"Ajijic","value":14},
            {"text":"Ameca","value":14},
            {"text":"Arandas","value":14},
            {"text":"Atotonilco el Alto","value":14},
            {"text":"Autlán de Navarro","value":14},
            {"text":"Chapala","value":14},
            {"text":"Cihuatlán","value":14},
            {"text":"Ciudad Guzmán","value":14},
            {"text":"Cocula","value":14},
            {"text":"Colotlán","value":14},
            {"text":"El Grullo","value":14},
            {"text":"El Quince (San José el Quince)","value":14},
            {"text":"Etzatlán","value":14},
            {"text":"Guadalajara","value":14},
            {"text":"Huejuquilla el Alto","value":14},
            {"text":"Jalostotitlán","value":14},
            {"text":"Jamay","value":14},
            {"text":"Jocotepec","value":14},
            {"text":"La Barca","value":14},
            {"text":"La Resolana","value":14},
            {"text":"Lagos de Moreno","value":14},
            {"text":"Las Pintitas","value":14},
            {"text":"Magdalena","value":14},
            {"text":"Ocotlán","value":14},
            {"text":"Poncitlán","value":14},
            {"text":"Puerto Vallarta","value":14},
            {"text":"San Diego de Alejandría","value":14},
            {"text":"San Ignacio Cerro Gordo","value":14},
            {"text":"San José el Verde (El Verde)","value":14},
            {"text":"San Juan de los Lagos","value":14},
            {"text":"San Julián","value":14},
            {"text":"San Miguel el Alto","value":14},
            {"text":"Sayula","value":14},
            {"text":"Tala","value":14},
            {"text":"Talpa de Allende","value":14},
            {"text":"Tamazula de Gordiano","value":14},
            {"text":"Tecalitlán","value":14},
            {"text":"Teocaltiche","value":14},
            {"text":"Tepatitlán de Morelos","value":14},
            {"text":"Tequila","value":14},
            {"text":"Tlajomulco de Zúñiga","value":14},
            {"text":"Tlaquepaque","value":14},
            {"text":"Tototlán","value":14},
            {"text":"Tuxpan","value":14},
            {"text":"Unión de San Antonio","value":14},
            {"text":"Valle de Guadalupe","value":14},
            {"text":"Villa Corona","value":14},
            {"text":"Villa Hidalgo","value":14},
            {"text":"Yahualica de González Gallo","value":14},
            {"text":"Zacoalco de Torres","value":14},
            {"text":"Zapopan","value":14},
            {"text":"Zapotiltic","value":14},
            {"text":"Apatzingán de la Constitución","value":15},
            {"text":"Ciudad Hidalgo","value":15},
            {"text":"Ciudad Lázaro Cárdenas","value":15},
            {"text":"Cotija de la Paz","value":15},
            {"text":"Cuitzeo del Porvenir","value":15},
            {"text":"Heroica Zitácuaro","value":15},
            {"text":"Huetamo de Núñez","value":15},
            {"text":"Jacona de Plancarte","value":15},
            {"text":"Jiquilpan de Juárez","value":15},
            {"text":"La piedad de Cabadas","value":15},
            {"text":"Las Guacamayas","value":15},
            {"text":"Los Reyes de Salgado","value":15},
            {"text":"Maravatío de Ocampo","value":15},
            {"text":"Morelia","value":15},
            {"text":"Nueva Italia de Ruiz","value":15},
            {"text":"Paracho de Verduzco","value":15},
            {"text":"Puruándiro","value":15},
            {"text":"Pátzcuaro","value":15},
            {"text":"Sahuayo de Morelos","value":15},
            {"text":"Tacámbaro de Codallos","value":15},
            {"text":"Tangancícuaro de Arista","value":15},
            {"text":"Uruapan","value":15},
            {"text":"Yurécuaro","value":15},
            {"text":"Zacapu","value":15},
            {"text":"Zamora de Hidalgo","value":15},
            {"text":"Zinapécuaro de Figueroa","value":15},
            {"text":"Cuautla (Cuautla de Morelos)","value":16},
            {"text":"Cuernavaca","value":16},
            {"text":"Galeana","value":16},
            {"text":"Jojutla","value":16},
            {"text":"Puente de Ixtla","value":16},
            {"text":"Santa Rosa Treinta","value":16},
            {"text":"Tlaquiltenango","value":16},
            {"text":"Zacatepec de Hidalgo","value":16},
            {"text":"Almoloya de Juárez","value":17},
            {"text":"Amatepec","value":17},
            {"text":"Atizapán de Zaragoza","value":17},
            {"text":"Capulhuac","value":17},
            {"text":"Chalco de Díaz Covarrubias","value":17},
            {"text":"Chiconcuac","value":17},
            {"text":"Chimalhuacán","value":17},
            {"text":"Ciudad Adolfo López Mateos","value":17},
            {"text":"Ciudad Nezahualcoyotl","value":17},
            {"text":"Coacalco de Berriozabal","value":17},
            {"text":"Cuautitlán","value":17},
            {"text":"Cuautitlán Izcalli","value":17},
            {"text":"Ecatepec de Morelos","value":17},
            {"text":"Huixquilucan de Degollado","value":17},
            {"text":"Ixtapaluca","value":17},
            {"text":"Juchitepec de Mariano Riva Palacio","value":17},
            {"text":"Los Reyes Acaquilpan (La Paz)","value":17},
            {"text":"Melchor Ocampo","value":17},
            {"text":"Metepec","value":17},
            {"text":"Naucalpan de Juárez","value":17},
            {"text":"Nezahualcóyotl","value":17},
            {"text":"Ocoyoacac","value":17},
            {"text":"San Mateo Atenco","value":17},
            {"text":"San Vicente Chicoloapan de Juárez","value":17},
            {"text":"Santa Maria Tultepec","value":17},
            {"text":"Tecamac de Felipe Villanueva","value":17},
            {"text":"Tejupilco de Hidalgo","value":17},
            {"text":"Tepotzotlán","value":17},
            {"text":"Tequixquiac","value":17},
            {"text":"Texcoco de Mora","value":17},
            {"text":"Tlalnepantla de Baz","value":17},
            {"text":"Toluca de Lerdo","value":17},
            {"text":"Tultitlán de Mariano Escobedo","value":17},
            {"text":"Valle de Chalco Solidaridad","value":17},
            {"text":"Villa Nicolás Romero","value":17},
            {"text":"Xonacatlán","value":17},
            {"text":"Zumpango","value":17},
            {"text":"Acaponeta","value":18},
            {"text":"Ahuacatlán","value":18},
            {"text":"Bucerías","value":18},
            {"text":"Compostela","value":18},
            {"text":"Francisco I. Madero (Puga)","value":18},
            {"text":"Ixtlán del Río","value":18},
            {"text":"Jala","value":18},
            {"text":"La peñita de Jaltemba","value":18},
            {"text":"Las Varas","value":18},
            {"text":"Ruiz","value":18},
            {"text":"San Blas","value":18},
            {"text":"San pedro Lagunillas","value":18},
            {"text":"Santiago Ixcuintla","value":18},
            {"text":"Tecuala","value":18},
            {"text":"Tepic","value":18},
            {"text":"Villa Hidalgo (El Nuevo)","value":18},
            {"text":"Xalisco","value":18},
            {"text":"Anáhuac","value":19},
            {"text":"Cadereyta Jiménez","value":19},
            {"text":"Ciudad Apodaca","value":19},
            {"text":"Ciudad Benito Juárez","value":19},
            {"text":"Ciudad General Escobedo","value":19},
            {"text":"Ciudad Sabinas Hidalgo","value":19},
            {"text":"Ciudad Santa Catarina","value":19},
            {"text":"Ciénega de Flores","value":19},
            {"text":"Doctor Arroyo","value":19},
            {"text":"El cercado","value":19},
            {"text":"García","value":19},
            {"text":"Guadalupe","value":19},
            {"text":"Hualahuises","value":19},
            {"text":"Linares","value":19},
            {"text":"Montemorelos","value":19},
            {"text":"Monterrey","value":19},
            {"text":"San Nicolás de los Garza","value":19},
            {"text":"San Pedro Garza García","value":19},
            {"text":"Santiago","value":19},
            {"text":"Asunción Nochixtlán","value":20},
            {"text":"Bahias de Huatulco","value":20},
            {"text":"Chahuites","value":20},
            {"text":"Ciudad Ixtepec","value":20},
            {"text":"Cosolapa","value":20},
            {"text":"Cuilápam de Guerrero","value":20},
            {"text":"El Camarón","value":20},
            {"text":"El Rosario","value":20},
            {"text":"Heroica Ciudad de Ejutla de Crespo","value":20},
            {"text":"Heroica Ciudad de Huajuapan de León","value":20},
            {"text":"Heroica Ciudad de Tlaxiaco","value":20},
            {"text":"Juchitán (Juchitán de Zaragoza)","value":20},
            {"text":"Lagunas","value":20},
            {"text":"Loma Bonita","value":20},
            {"text":"Mariscala de Juárez","value":20},
            {"text":"Matías Romero Avendaño","value":20},
            {"text":"Miahuatlán de Porfirio Díaz","value":20},
            {"text":"Natividad","value":20},
            {"text":"Oaxaca de Juárez","value":20},
            {"text":"Ocotlán de Morelos","value":20},
            {"text":"Puerto Escondido","value":20},
            {"text":"Putla Villa de Guerrero","value":20},
            {"text":"Río Grande o Piedra Parada","value":20},
            {"text":"Salina Cruz","value":20},
            {"text":"San Antonio de la Cal","value":20},
            {"text":"San Blas Atempa","value":20},
            {"text":"San Felipe Jalapa de Díaz","value":20},
            {"text":"San Francisco Ixhuatán","value":20},
            {"text":"San Francisco Telixtlahuaca","value":20},
            {"text":"San Juan Bautista Cuicatlán","value":20},
            {"text":"San Juan Bautista Tuxtepec","value":20},
            {"text":"San Juan Bautista Valle Nacional","value":20},
            {"text":"San Juan Bautista lo de Soto","value":20},
            {"text":"San Juan Cacahuatepec","value":20},
            {"text":"San Miguel el Grande","value":20},
            {"text":"San Pablo Huitzo","value":20},
            {"text":"San Pablo Villa de Mitla","value":20},
            {"text":"San Pedro Mixtepec -Dto. 22-","value":20},
            {"text":"San Pedro Pochutla","value":20},
            {"text":"San Pedro Tapanatepec","value":20},
            {"text":"San Pedro Totolapa","value":20},
            {"text":"San Sebastián Tecomaxtlahuaca","value":20},
            {"text":"Santa Cruz Itundujia","value":20},
            {"text":"Santa Lucia del Camino","value":20},
            {"text":"Santa María Huatulco","value":20},
            {"text":"Santiago Jamiltepec","value":20},
            {"text":"Santiago Juxtlahuaca","value":20},
            {"text":"Santiago Pinotepa Nacional","value":20},
            {"text":"Santiago Suchilquitongo","value":20},
            {"text":"Santo Domingo Tehuantepec","value":20},
            {"text":"Teotitlán de Flores Magón","value":20},
            {"text":"Tlacolula de Matamoros","value":20},
            {"text":"Unión Hidalgo","value":20},
            {"text":"Vicente Camalote","value":20},
            {"text":"Villa Sola de Vega","value":20},
            {"text":"Villa de Tamazulápam del Progreso","value":20},
            {"text":"Villa de Zaachila","value":20},
            {"text":"Zimatlán de Álvarez","value":20},
            {"text":"Acatlán de Osorio","value":21},
            {"text":"Amozoc","value":21},
            {"text":"Atlixco","value":21},
            {"text":"Ciudad Serdán","value":21},
            {"text":"Cuautlancingo","value":21},
            {"text":"Huauchinango","value":21},
            {"text":"Izúcar de Matamoros","value":21},
            {"text":"Puebla (Heroica Puebla)","value":21},
            {"text":"San Andrés Cholula","value":21},
            {"text":"San Martín Texmelucan de Labastida","value":21},
            {"text":"San Pedro Cholula","value":21},
            {"text":"Tecamachalco","value":21},
            {"text":"Tehuacan","value":21},
            {"text":"Tepeaca","value":21},
            {"text":"Teziutlan","value":21},
            {"text":"Xicotepec","value":21},
            {"text":"Zacatlán","value":21},
            {"text":"El Pueblito","value":22},
            {"text":"Querétaro","value":22},
            {"text":"San Juan del Rio","value":22},
            {"text":"Bacalar","value":23},
            {"text":"Cancún","value":23},
            {"text":"Chetumal","value":23},
            {"text":"Cozumel","value":23},
            {"text":"Felipe Carrillo Puerto","value":23},
            {"text":"Isla Mujeres","value":23},
            {"text":"Kantunilkín","value":23},
            {"text":"Playa del Carmen","value":23},
            {"text":"Cedral","value":24},
            {"text":"Cerritos","value":24},
            {"text":"Charcas","value":24},
            {"text":"Ciudad Valles","value":24},
            {"text":"Ciudad del Maíz","value":24},
            {"text":"Cárdenas","value":24},
            {"text":"El Naranjo","value":24},
            {"text":"Fracción el Refugio","value":24},
            {"text":"Matehuala","value":24},
            {"text":"Rioverde","value":24},
            {"text":"Salinas de Hidalgo","value":24},
            {"text":"San Luis Potosí","value":24},
            {"text":"Santa María del Río","value":24},
            {"text":"Soledad de Graciano Sánchez","value":24},
            {"text":"Tamasopo","value":24},
            {"text":"Tamazunchale","value":24},
            {"text":"Tamuin","value":24},
            {"text":"Tierra Nueva","value":24},
            {"text":"Villa de Reyes","value":24},
            {"text":"Ébano","value":24},
            {"text":"Aguaruto","value":25},
            {"text":"Ahome","value":25},
            {"text":"Angostura","value":25},
            {"text":"Choix","value":25},
            {"text":"Cosalá","value":25},
            {"text":"Culiacán Rosales","value":25},
            {"text":"Escuinapa de Hidalgo","value":25},
            {"text":"Estación Naranjo","value":25},
            {"text":"Guamúchil","value":25},
            {"text":"Guasave","value":25},
            {"text":"Higuera de Zaragoza","value":25},
            {"text":"La Cruz","value":25},
            {"text":"Lic. Benito Juárez (Campo Gobierno)","value":25},
            {"text":"Los Mochis","value":25},
            {"text":"Mazatlán","value":25},
            {"text":"Mocorito","value":25},
            {"text":"Navolato","value":25},
            {"text":"Quila","value":25},
            {"text":"Sinaloa de Leyva","value":25},
            {"text":"Topolobampo","value":25},
            {"text":"Villa Unión","value":25},
            {"text":"Agua Prieta","value":26},
            {"text":"Ciudad Obregón","value":26},
            {"text":"Empalme","value":26},
            {"text":"Hermosillo","value":26},
            {"text":"Heroica Caborca","value":26},
            {"text":"Heroica Ciudad de Cananea","value":26},
            {"text":"Heroica Guaymas","value":26},
            {"text":"Heroica Nogales","value":26},
            {"text":"Huatabampo","value":26},
            {"text":"Magdalena de Kino","value":26},
            {"text":"Navojoa","value":26},
            {"text":"Puerto Peñasco","value":26},
            {"text":"San Luis Río Colorado","value":26},
            {"text":"Sonoita","value":26},
            {"text":"Comalcalco","value":27},
            {"text":"Cunduacán","value":27},
            {"text":"Emiliano Zapata","value":27},
            {"text":"Huimanguillo","value":27},
            {"text":"Jalpa de Méndez","value":27},
            {"text":"Macuspana","value":27},
            {"text":"Paraíso","value":27},
            {"text":"Teapa","value":27},
            {"text":"Tenosique de Pino Suárez","value":27},
            {"text":"Villahermosa","value":27},
            {"text":"Altamira","value":28},
            {"text":"Ciudad Camargo","value":28},
            {"text":"Ciudad Gustavo Díaz Ordaz","value":28},
            {"text":"Ciudad Madero","value":28},
            {"text":"Ciudad Mante","value":28},
            {"text":"Ciudad Miguel Alemán","value":28},
            {"text":"Ciudad Río Bravo","value":28},
            {"text":"Ciudad Tula","value":28},
            {"text":"Ciudad Victoria","value":28},
            {"text":"Estación Manuel (Úrsulo Galván)","value":28},
            {"text":"González","value":28},
            {"text":"Heroica Matamoros","value":28},
            {"text":"Jaumave","value":28},
            {"text":"Nueva Ciudad Guerrero","value":28},
            {"text":"Nuevo Laredo","value":28},
            {"text":"Reynosa","value":28},
            {"text":"San Fernando","value":28},
            {"text":"Soto la Marina","value":28},
            {"text":"Tampico","value":28},
            {"text":"Valle Hermoso","value":28},
            {"text":"Xicoténcatl","value":28},
            {"text":"Apizaco","value":29},
            {"text":"Calpulalpan","value":29},
            {"text":"Chiautempan","value":29},
            {"text":"Huamantla","value":29},
            {"text":"Tlaxcala (Tlaxcala de Xicotencatl)","value":29},
            {"text":"Villa Vicente Guerrero","value":29},
            {"text":"Acayucan","value":30},
            {"text":"Agua dulce","value":30},
            {"text":"Altotonga","value":30},
            {"text":"Alvarado","value":30},
            {"text":"Atoyac","value":30},
            {"text":"Banderilla","value":30},
            {"text":"Boca del RÍo","value":30},
            {"text":"Carlos A. Carrillo","value":30},
            {"text":"Catemaco","value":30},
            {"text":"Cazones de Herrera","value":30},
            {"text":"Cerro Azul","value":30},
            {"text":"Coatepec","value":30},
            {"text":"Coatzacoalcos","value":30},
            {"text":"Coatzintla","value":30},
            {"text":"Cosamaloapan","value":30},
            {"text":"Cosoleacaque","value":30},
            {"text":"Cuichapa","value":30},
            {"text":"Cuitláhuac","value":30},
            {"text":"Córdoba","value":30},
            {"text":"El Higo","value":30},
            {"text":"Fortín de las Flores","value":30},
            {"text":"General Miguel Alemán (Potrero Nuevo)","value":30},
            {"text":"Gutiérrez Zamora","value":30},
            {"text":"Huatusco de Chicuellar","value":30},
            {"text":"Huayacocotla","value":30},
            {"text":"Huiloapan de Cuauhtémoc","value":30},
            {"text":"Isla","value":30},
            {"text":"Ixtaczoquitlán","value":30},
            {"text":"José Cardel","value":30},
            {"text":"Juan Díaz Covarrubias","value":30},
            {"text":"Juan Rodríguez Clara","value":30},
            {"text":"Jáltipan de Morelos","value":30},
            {"text":"Las Choapas","value":30},
            {"text":"Lerdo de Tejada","value":30},
            {"text":"Minatitlán","value":30},
            {"text":"Naranjos","value":30},
            {"text":"Nogales","value":30},
            {"text":"Orizaba","value":30},
            {"text":"Papantla de Olarte","value":30},
            {"text":"Paraje Nuevo","value":30},
            {"text":"Paso de Ovejas","value":30},
            {"text":"Paso del Macho","value":30},
            {"text":"Platón Sánchez","value":30},
            {"text":"Playa Vicente","value":30},
            {"text":"Poza Rica de Hidalgo","value":30},
            {"text":"Pánuco","value":30},
            {"text":"Río Blanco","value":30},
            {"text":"San Andrés Tuxtla","value":30},
            {"text":"San Rafael","value":30},
            {"text":"Santiago Tuxtla","value":30},
            {"text":"Sihuapan","value":30},
            {"text":"Soledad de Doblado","value":30},
            {"text":"Tampico Alto","value":30},
            {"text":"Tantoyuca","value":30},
            {"text":"Tempoal de Sánchez","value":30},
            {"text":"Tezonapa","value":30},
            {"text":"Tierra Blanca","value":30},
            {"text":"Tihuatlán","value":30},
            {"text":"Tlacojalpan","value":30},
            {"text":"Tlapacoyan","value":30},
            {"text":"Tres Valles","value":30},
            {"text":"Túxpam de Rodríguez Cano","value":30},
            {"text":"Veracruz","value":30},
            {"text":"Xalapa-Enríquez","value":30},
            {"text":"Yecuatla","value":30},
            {"text":"Ángel R. Cabada","value":30},
            {"text":"Motul de Carrillo Puerto","value":31},
            {"text":"Mérida","value":31},
            {"text":"Ticul","value":31},
            {"text":"Tizimín","value":31},
            {"text":"Valladolid","value":31},
            {"text":"Ciudad Cuauhtémoc","value":32},
            {"text":"Fresnillo","value":32},
            {"text":"Jalpa","value":32},
            {"text":"Jerez de García Salinas","value":32},
            {"text":"Luis Moya","value":32},
            {"text":"Moyahua de Estrada","value":32},
            {"text":"Nochistlán de Mejía","value":32},
            {"text":"Ojocaliente","value":32},
            {"text":"Río Grande","value":32},
            {"text":"Sombrerete","value":32},
            {"text":"Valparaíso","value":32},
            {"text":"Villa de Cos","value":32},
            {"text":"Villanueva","value":32},
            {"text":"Víctor Rosales","value":32},
            {"text":"Zacatecas","value":32}
        ]
    }
});